### ISSUE TITLE
TransformError

### ISSUE THREAD

**Issue by githubxiaotian** [togayther/react-native-cnblogs#29]
error: bundling: Error: Couldn't find preset "react-native" relative to directory "/Users/tyh/Desktop/workspace"
    at /Users/tyh/Desktop/workspace/react-native-cnblogs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/tyh/Desktop/workspace/react-native-cnblogs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/tyh/Desktop/workspace/react-native-cnblogs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/tyh/Desktop/workspace/react-native-cnblogs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/tyh/Desktop/workspace/react-native-cnblogs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/tyh/Desktop/workspace/react-native-cnblogs/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/tyh/Desktop/workspace/react-native-cnblogs/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/tyh/Desktop/workspace/react-native-cnblogs/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
TransformError: /Users/tyh/Desktop/workspace/react-native-cnblogs/index.android.js: Couldn't find preset "react-native" relative to directory "/Users/tyh/Desktop/workspace"
Bundling `index.android.js`  0.0(0/1), failed.

**Comment by togayther** [comment]
@githubxiaotian 
你好，请安装 react-native-cli。 相关命令为： npm i react-native-cli -g
